# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

-- apply changes
create table tile (
  id                            integer generated by default as identity not null,
  card_id                       integer not null,
  x                             integer not null,
  y                             integer not null,
  rotation                      integer not null,
  constraint pk_tile primary key (id)
);


# --- !Downs

-- drop all
drop table if exists tile;

